<a href="https://colab.research.google.com/github/Arkaprabha1012/Datascience/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#value
t1=torch.tensor(4.)
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
#vector
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
#matrix
t3=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
#3 dimensional array
t4=torch.tensor([[[11,12,23],[89,43,78]],[[15,16,12],[54,65,76]]])
t4

tensor([[[11, 12, 23],
         [89, 43, 78]],

        [[15, 16, 12],
         [54, 65, 76]]])

In [ ]:
#value
t1.shape

torch.Size([])

In [ ]:
#array
t2.shape

torch.Size([4])

In [ ]:
#matrix
t3.shape

torch.Size([4, 2])

In [ ]:
#3d matrix
t4.shape

torch.Size([2, 2, 3])

In [ ]:
##TENSOR OPERATIONS AND GRADIENTS

In [ ]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [ ]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
#computer derivatives
y.backward()

In [ ]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
#WITH NUMPY,MATPLOTLIB,OPENCV,PANDAS

In [ ]:
import numpy as np
x=np.array([[1,2],[3.,4]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
#Creating torch tensor from numpy
y=torch.tensor(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [ ]:
#Tensor to numpy
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [1]:
import numpy as np
import torch

In [4]:
#input temp raifall humidity
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')
#input taget variables (apples,oranges)
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

In [5]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs,"\n",targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### **LINEAR REGRESSION USING GRADIENT DESCENT**

yield_apple=w11*temp+w12*rainfall+w13*humidity+b1

yield_orange=w21*temp+w22*rainfall+w23*humidity+b2

In [31]:
w=torch.randn(2,3,requires_grad=True)#WE HAVE THREE INPUT AND TWO TARGETS
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.0099,  1.0852,  1.6666],
        [ 0.0430, -0.8863, -0.4078]], requires_grad=True)
tensor([-0.8850, -1.3959], requires_grad=True)


X  x WT(Transpos of W) + b

In [32]:
def model(x):
  return x @ w.t() + b
#@ means matrix multiplication in PYTORCH .t is for transpos

In [33]:
preds=model(inputs)
preds

tensor([[ 144.2041,  -75.1754],
        [ 202.1684, -101.5777],
        [ 242.0468, -140.0743],
        [ 108.4466,  -50.2095],
        [ 220.6323, -112.0612]], grad_fn=<AddBackward0>)

In [34]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


LOSS FUNCTION

In [35]:
#MSE(Mean Squared Error) LOSS 
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [36]:
loss=mse(preds,targets)
print(loss)

tensor(25659.0547, grad_fn=<DivBackward0>)


### COMPUTE GRADIENTS

In [37]:
loss.backward()

In [38]:
print(w)
print(w.grad)

tensor([[ 0.0099,  1.0852,  1.6666],
        [ 0.0430, -0.8863, -0.4078]], requires_grad=True)
tensor([[  9020.8945,   9614.1328,   6023.4102],
        [-15525.6846, -18015.4844, -10889.3711]])


In [39]:
print(b)
print(b.grad)

tensor([-0.8850, -1.3959], requires_grad=True)
tensor([ 107.2996, -187.8196])


### GRADIENT DESCENT

In [41]:
'''w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)'''

'w.grad.zero_()\nb.grad.zero_()\nprint(w.grad)\nprint(b.grad)'

In [45]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [46]:
print(w)
print(b)

tensor([[-0.0803,  0.9890,  1.6064],
        [ 0.1983, -0.7062, -0.2989]], requires_grad=True)
tensor([-0.8861, -1.3940], requires_grad=True)


In [48]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(17515.9590, grad_fn=<DivBackward0>)


In [59]:
for i in range(2000):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5  #1e-5 is learning rate
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [60]:
#calculate loss
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(0.5421, grad_fn=<DivBackward0>)


In [61]:
preds

tensor([[ 56.9952,  70.0952],
        [ 82.4692, 100.6564],
        [118.3668, 133.3290],
        [ 21.0022,  37.1378],
        [102.2465, 118.7682]], grad_fn=<AddBackward0>)

In [62]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])